GLLoad(GENBUFFERS, GenBuffers);
GLLoad(BINDBUFFER, BindBuffer);
GLLoad(BUFFERDATA, BufferData);

GLLoad(VERTEXATTRIBPOINTER, VertexAttribPointer);
GLLoad(ENABLEVERTEXATTRIBARRAY, EnableVertexAttribArray);

GLLoad(CREATESHADER, CreateShader);
GLLoad(SHADERSOURCE, ShaderSource);
GLLoad(COMPILESHADER, CompileShader);
GLLoad(GETSHADERIV, GetShaderiv);
GLLoad(GETSHADERINFOLOG, GetShaderInfoLog);
GLLoad(CREATEPROGRAM, CreateProgram);
GLLoad(ATTACHSHADER, AttachShader);
GLLoad(LINKPROGRAM, LinkProgram);
GLLoad(GETPROGRAMIV, GetProgramiv);
GLLoad(GETPROGRAMINFOLOG, GetProgramInfoLog);
GLLoad(USEPROGRAM, UseProgram);
GLLoad(DELETESHADER, DeleteShader);

GLLoad(GETUNIFORMLOCATION, GetUniformLocation);
GLLoad(UNIFORM3F, Uniform3f);
